config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "equipments#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, :only => [:show]

  resources :equipments do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: [:index, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :equipment

  validates :start_date, :end_date, presence: true
  enum status: [ :pending, :confirmed, :cancelled  ]

  # before_save :end_date_after_start_date

  # private

  # def end_date_after_start_date
  #   return if end_date.blank? || start_date.blank?

  #   if end_date < start_date
  #     errors.add(:end_date, "must be after the start date")
  #   end
  # end
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  CATEGORY = ["tents", "ski", "caravans", "hiking", "surf"]
  before_create :capitalize

  has_many_attached :photos
  belongs_to :user
  has_many :bookings

  validates :name, :description, :category, :price, presence: true
  validates :category, inclusion: { in: CATEGORY }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_equipment,
                  against: %i[name category description],
                  using: {
                    tsearch: { prefix: true }
                  }

  private
    def capitalize
      self.name = self.name.downcase
      self.name = self.name.capitalize!
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :equipments, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :received_bookings, through: :equipments, source: :bookings

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username address photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username address photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @my_bookings = Booking.all.where(user_id: current_user.id)
    @received_bookings = current_user.received_bookings
    @pending_bookings = current_user.received_bookings.where(status: "pending")
  end

  def new
    @equipment = Equipment.find(params[:equipment_id])
    @booking = Booking.new
  end

  def create
    @equipment = Equipment.find(params[:equipment_id])
    @booking = Booking.new(booking_params)
    @booking.equipment = @equipment
    @booking.user = current_user
    @booking.total_price = ((@booking.end_date - @booking.start_date) * @equipment.price)
    @booking.save

    redirect_to bookings_path
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(status: params[:status])
    redirect_to user_path(current_user)
    #get params sent by booking index and update status of booking accordingly
  end

  def destroy
    @booking.destroy
    redirect_to equipments_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:equipment_id, :user_id, :status, :start_date, :end_date, :total_price)
  end

end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :update, :destroy]
  def index
    if params[:query].present?
      @equipments = Equipment.search_equipment(params[:query])
    else
      @equipments = Equipment.all
    end

    @markers = @equipments.geocoded.map do |equipment|
      {
        lat: equipment.latitude,
        lng: equipment.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { equipment: equipment })
      }
    end
  end

  def new
    @equipment = Equipment.new
  end

  def create
    @equipment = Equipment.new(equipment_params)
    @equipment.user = current_user

    if @equipment.save
      redirect_to equipment_path(@equipment)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @equipment = Equipment.find(params[:id])
    @booking = Booking.new
    @markers = [{
      lat: @equipment.latitude,
      lng: @equipment.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {equipment: @equipment})
    }]
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def update
    @equipment = Equipment.find(params[:id])
    if @equipment.update(equipment_params)
      redirect_to equipment_path(@equipment)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy

    redirect_to equipments_path, status: :see_other
  end

  private

  def equipment_params
    params.require(:equipment).permit(:name, :description, :address, :price, :category, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @my_bookings = Booking.all.where(user_id: current_user.id)
    @received_bookings = current_user.received_bookings
    @pending_bookings = current_user.received_bookings.where(status: "pending")
    @confirmed_bookings = current_user.received_bookings.where(status: "confirmed")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<div class="booking-form-show">
  <h4 class="mb-4" style="font-weight: 700;">Renting <%= @equipment.name %></h4>
  <%= simple_form_for [@equipment, @booking] do |f| %>
    <%= f.input :start_date, as: :string, input_html: { data: { controller: "flatpickr" } } %>
    <%= f.input :end_date, as: :string, input_html: { data: { controller: "flatpickr" } } %>
    <%= f.submit %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="container-booking" style="height:575px;">
  <br>
        <div class="goback-button"><%= link_to "← Go back", :back %></div>
        <% unless @my_bookings.nil? %>
          <h4>Requested bookings</h4>
          <ul class="list-inline">
            <% @my_bookings.each do |booking| %>
              <%= link_to equipment_path(booking.equipment) do %>
            <div class="submittedbooking-card">
              <%= cl_image_tag booking.equipment.photos.first.key %>
              <div class="submittedbooking-card-text">
                <strong><%= booking.equipment.name %></strong><br>
                <%= booking.start_date %> - <%= booking.end_date %>. <br>
                Total price: <%= booking.total_price %>€ <br>
                Status:
                <% if booking.status == "pending" %>
                  <span style = "color:#D3713C"><strong><%= booking.status %></strong></span>.
                <% elsif booking.status == "confirmed" %>
                  <span style = "color:#2B5242"><strong><%= booking.status %></strong></span>.
                <% elsif booking.status == "cancelled" %>
                  <span style = "color:#A33407"><strong><%= booking.status %></strong></span>.
                <% end %>
              </div>
            </div>
          </ul>
          <% end %>
          <% end %>
        <% end %>
  </div>
</div>
</div>

app/views/equipments/_info_window.html.erb
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
   <div class="carousel-item active">
      <%= cl_image_tag equipment.photos.first.key, height: '130px', width:'220px'%>
    </div>
     <% equipment.photos.each do |photo| %>
     <% next if photo == equipment.photos[0] %>
      <div class="carousel-item">
        <%= cl_image_tag photo.key, height: '130px', width:'220px'%>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>




<div class="map-image"><%=link_to equipment.name, equipment_path(equipment) %></div>
<p><%= equipment.description %></p>

app/views/equipments/edit.html.erb
<div class="most-supreme-form-container signup-fill">
  <div class="most-supreme-form-container">
    <div class="supreme-form-container">
      <div class="container">
        <div class="goback-button goback-button-edit mx-auto">
          <%= link_to equipments_path do %>
            <i class="fa-solid fa-arrow-left" style="margin-right: 5px"></i>
            Go back
          <% end %>
        </div>

        <div class="form-container m-auto">
          <h2>Edit equipment</h2>

          <%= simple_form_for @equipment do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%#= f.input :photos, as: :file, input_html: { multiple: true } %>
            <%= f.submit "Submit", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/equipments/index.html.erb
<% unless params[:query].present? %>
  <div class="container">
    <div class="hero">
      <div class="hero-box-one">
        <h2>CATCH ADVENTURES, NOT FEELINGS</h2>
        <%= link_to "Add equipment now", new_equipment_path, class: "hero-button" %>
      </div>
      <div class="hero-box-two"><p>Renting equipment for hiking, camping, and sports refers to the practice of temporarily leasing outdoor gear and equipment for recreational activities such as backpacking, camping, skiing, or snowboarding. Renting allows individuals to access specialized gear without the expense of purchasing and maintaining it themselves.</p>

      <p><i class="fa-solid fa-heart"></i>&nbsp; With love, from <strong>ToGo</strong> team</p></div>
    </div>
  </div>

</div>
<div data-controller = "toggle_map map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  <button data-action="click->toggle_map#toggle click->map#resize" class="show-button" style="box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);">show map</button>

  <div class="container">

<% end %>


<div class="container" >
    <div style="margin-top: 50px; margin-bottom: 50px;"><%= render "shared/iconmenu" %></div>


<% unless params[:query].present? %>
    <div><h2 id="available-equipment" style="margin-top: 50px; margin-bottom: 50px; font-size: 36px; font-weight: 700;">Available equipment</h2>
</div><% end %>
      <div class="equipment-cards equipments-container" data-toggle_map-target="cards">
        <% @equipments.each do |equipment| %>
          <%= link_to equipment_path(equipment) do %>
            <div class="equipment-card">


              <!-- Start of carrousel -->
              <div id="carouselExampleControls<%= equipment.id %>" class="carousel slide" data-bs-ride="false">
                  <div class="carousel-inner" style="border-radius: 25px;">
                  <div class="carousel-item active">
                      <%= cl_image_tag equipment.photos.first.key, height: '250px', width:'100%', style: "object-fit: cover"%>
                    </div>
                    <% equipment.photos[1..].each do |photo| %>
                    <%# next if photo == equipment.photos[0] %>
                      <div class="carousel-item">
                        <%= cl_image_tag photo.key, height: '250px', width:'100%', style: "object-fit: cover"%>
                      </div>
                    <% end %>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls<%= equipment.id %>" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls<%= equipment.id %>" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>


              </div>

              <!-- End of carrousel -->

              <div class="equipment-card-info">
                <!-- <div class="d-flex align-items-center">
                  <div class="card-info-username-img"></div>
                  <strong><%= equipment.user.username %></strong>
                </div> -->

                <div class="w-100 d-flex justify-content-between align-items-center">
                  <div><h4><%#= equipment.name %><td><%= equipment.name.length > 25 ? "#{equipment.name[0..22]}..." : equipment.name %></td></h4></div>
                  <div><h5><%= equipment.price %>€/day</h5></div>
                </div>

                <div style="margin-top:10px;"><%#= equipment.description %><td><%= equipment.description.length > 83 ? "#{equipment.description[0..80]}..." : equipment.description %></td></div>

                <div class="equipment-card-category">#<%= equipment.category %></div>

              </div>
            </div>
          <% end %>
        <% end %>
      </div>

  </div>
  <div id="map" style="visibility: hidden; width: 100%; height:0; margin-bottom: 50px;" data-map-target="map" data-toggle_map-target="map">
  </div>
</div>

app/views/equipments/new.html.erb
<div class="most-supreme-form-container">
  <div class="supreme-form-container">
    <div class="container">

      <div class="form-container">
        <h2>Add equipment</h2>
          <%= simple_form_for @equipment, url: equipments_path do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :address %>
            <%= f.input :price %>
            <%= f.input :category, collection: Equipment::CATEGORY %>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            <%= f.submit "Submit", class: 'button' %>
          <% end %>
      </div>

    </div>
  </div>
</div>

app/views/equipments/show.html.erb
<div class="equipment-container"
     data-controller="map"
     data-map-markers-value="<%= @markers.to_json %>"
     data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  <div class="container">
    <div class="equipment-buttons d-flex justify-content-between">
      <div class="goback-button">
        <%= link_to equipments_path do %>
          <i class="fa-solid fa-arrow-left" style="margin-right: 5px"></i>
          Go back
        <% end %>

      </div>

      <% if @equipment.user == current_user %>
        <div class="equipment-edit-buttons d-flex">
          <%= link_to edit_equipment_path(@equipment) do %>
            <i class="fa-solid fa-pen" style="margin-right: 5px"></i>
            Edit equipment
          <% end %>

          <%= button_to equipment_path(@equipment), method: :delete, data: {turbolinks: false, confirm: "Are you sure?"} do %>
            <i class="fa-solid fa-trash" style="margin-right: 5px"></i>
            Delete equipment
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="equipment-show">
      <!-- Left side -->
      <div class="equipment-show-right">
        <div class="equipment-description">
          <h2 style="font-weight: 700;"><%= @equipment.name %></h2>
          <p>Listed by <strong><%= @equipment.user.username %></strong></p>

          <h4><strong>€<%= @equipment.price %></strong> per day</h4>

          <p>Description: <%= @equipment.description %></p>

          <span style="color: grey"> #<%= @equipment.category %></span>
        </div>

        <div class="new-booking-container">
          <%= render "bookings/new", equipment: @equipment, booking: @booking %>
        </div>
      </div>

      <!-- Right side -->
      <div class="equipment-side">
        <div class="equipment-images">
          <% if @equipment.photos.attached?  %>
            <% @equipment.photos.each do |photo|  %>
              <%= cl_image_tag photo.key %>
            <% end %>
          <% end %>
        </div>


      </div>
    </div>
    <hr>
    <h2>Where I live?</h2>
    <div class="map-side" style="width: 100%; height: 500px;" data-map-target="map"></div>
  </div>
    <p style="margin-left: 70px; margin-top: 20px"><%= @equipment.address %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Go</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
  </head>



  <body>
    <% if notice %>

      <div class="flash flash-success alert alert-dismissible fade show" role="alert">
        <span><strong><%= notice %></strong></span>
        <a data-bs-dismiss="alert" aria-label="Close">
          &nbsp;&nbsp;<i class="fas fa-times"></i>
        </a>
      </div>

      <!-- <p class="notice"><%= notice %></p> -->
    <% end %>

    <% if alert %>
    <p class="alert"><%= alert %></p>
    <% end %>

    <%= render "shared/navbar" %>
      <%= yield %>
    <%= render "shared/footer" %>
  </body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% @users.each do |user| %>
  <%= user.equipment.name %>
  <%= user.equipment.price %>
<% end %>

app/views/shared/_footer.html.erb
          <div class="footer">
              <div class="footer-links">
                <a href="https://github.com"><i class="fab fa-github"></i></a>
                <a href="https://instagram.com"><i class="fab fa-instagram"></i></a>
                <a href="https://facebook.com"><i class="fab fa-facebook"></i></a>
                <a href="https://twitter.com"><i class="fab fa-twitter"></i></a>
                <a href="https://linkedin.com"><i class="fab fa-linkedin"></i></a>
              </div>
              <div class="footer-copyright">
               <i class="fas fa-heart"></i> Chillpill team ® 2023. All rights reserved
              </div>
          </div>

app/views/shared/_iconmenu.html.erb
<div class="container px-0">
  <div class="icon-container">

    <div class="icon-category"><a href="/?query=hiking"><i class="fa-solid fa-person-hiking" style="font-size: 40px"></i><br>Hiking</a></div>
    <div class="icon-category"><a href="/?query=tents"><i class="fa-solid fa-campground" style="font-size: 40px"></i><br>Tents</a></div>
    <div class="icon-category"><a href="/?query=ski"><i class="fa-solid fa-person-skiing" style="font-size: 40px"></i><br>Ski</a></div>
    <div class="icon-category"><a href="/?query=surf"><i class="fa-solid fa-water" style="font-size: 40px"></i><br>Surf</a></div>
    <div class="icon-category"><a href="/?query=caravan"><i class="fa-solid fa-caravan" style="font-size: 40px"></i><br>Caravans</a></div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

  <%=link_to image_tag("logo.png", alt: "My Logo", class: "logo"), equipments_path %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= simple_form_for :search, url: equipments_path, method: :get do |f| %>
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="query" id="query" placeholder="Find equipment" value="" />
        <button name="button" type="submit" name="commit" class="btn btn-flat" data-disable-with="Search">
          <i class="fas fa-search"></i>
        </button>
      </div>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if current_user %>
          <li class="nav-item active">
            <%= link_to "Home", equipments_path , class: "nav-link" %>
             <li><%= link_to "Add Equipment", new_equipment_path, class: "nav-link" %></li>
             <li><%#= link_to "Logout", new_user_session_path, class: "nav-link" %></li>
          </li>

          <li class="nav-item dropdown">
          <% unless current_user.photo.key.nil? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
                    <%# raise %>
            <%= image_tag "user", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "View profile", user_path(id: current_user.id), class: "dropdown-item" %>
              <%= link_to "Edit details", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "See my bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="profile-container" >
  <div class="goback-button"><%= link_to "← Go back", equipments_path %></div>

    <div class = "container d-flex justify-content-between">
      <div class = "profile-show">
        <!-- Left side -->
        <div class = "profile-right">
          <div class = "profile-description">
            <h2 style="font-weight: 700;">My Profile</h2>
            <% unless current_user.photo.key.nil? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar-large"%>
            <% else %>
              <%= image_tag "user", class: "avatar-large" %>
            <% end %>
           <p><strong> <%= current_user.username %></strong> </p>
            <p> Member since: <%= current_user.created_at.strftime("%B #{current_user.created_at.day.ordinalize}, %Y") %> </p>
          </div>

          <% unless @my_bookings.empty? %>
            <div class="order-container">
              <div class = "order-description">
                <h2 style="font-weight: 700;">My Submitted Bookings</h2>
                <span class="goback-button"><%= link_to "See all", bookings_path %></span><br>
                <ol class= "list-inline">
                <br>
                  <li><strong>Most recent:</strong></li><br>
                  <li><span style="color:grey"><%= @my_bookings.last.equipment.name %> from <%= @my_bookings.last.equipment.user.username %>.  <br>Status: <%= @my_bookings.last.status %> </span></li>
              </div>
            </div>
          <% else %>
          <p><strong>No recent bookings</strong></p>
          <% end %>
        </div>
      </div>

      <div class="profile-side">
        <!-- right side -->
        <div class="profile-images">
          <h2 style="font-weight: 700;">Received bookings</h2>

          <p><strong>Pending</strong></p>
          <% if @pending_bookings.empty? %>
            <p>No bookings yet :(</p>
          <% else %>
            <% @pending_bookings.each do|booking| %>
              <div class="card-product">
                  <%= cl_image_tag booking.equipment.photos.first.key %>
                <div class="d-flex justify-content-between w-100 card-product-infos">
                  <div>
                  <p><%= booking.equipment.name %> <strong>status</strong> <%=booking.status%> </p>
                  <p><strong>Dates: </strong><%= booking.start_date %> to <%= booking.end_date %></p>
                  <p><strong>Total price: </strong><%= booking.total_price %>€ </p>
                  <p><strong>Requested by: </strong><%= booking.user.username %> </p>
                  </div>

                  <div class="d-flex align-items-center">
                    <div class="confirm-btn">
                      <%= button_to "Confirm",  booking_path(booking, {status: "confirmed"}), method: :patch, data: {turbo_confirm: 'Are you sure?'} %>
                    </div>

                      <div class="reject-btn">
                        <%= button_to "Reject",  booking_path(booking, {status: "cancelled"}), method: :patch, data: {turbo_confirm: 'Are you sure?'} %>
                      </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>

          <p><strong>Confirmed</strong></p>
          <% @confirmed_bookings.each do|booking| %>
            <div class="card-product">
              <%= cl_image_tag booking.equipment.photos.first.key %>
              <div class="d-flex w-100 justify-content-between card-product-infos">
                <div>
                  <p><%= booking.equipment.name %> <strong>status</strong> <%=booking.status%> </p>
                  <p><%= booking.start_date %> to <%= booking.end_date %></p>
                  <p><strong>Total price: </strong><%= booking.total_price %>€ </p>
                  <p><strong>Requested by: </strong><%= booking.user.username %> </p>

                </div>
                <div class="reject-btn d-flex">
                  <%= button_to "Reject",  booking_path(booking, {status: "cancelled"}), method: :patch, data: {turbo_confirm: 'Are you sure?'} %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>